"use client";

import Image from "next/image";
import { FormEvent, ReactNode, useMemo, useState } from "react";
import { BarChart3, Boxes, CircleDollarSign, ClipboardList, LayoutDashboard, Menu, PackagePlus, Plus, Search, Settings, ShoppingCart, UsersRound, X } from "lucide-react";
import { initialCustomers, initialProducts, money, type Customer, type Product } from "@/lib/erp";

type Section = "Visão geral" | "Vendas" | "Clientes" | "Produtos" | "Estoque" | "Financeiro" | "Configurações";
type Dialog = "customer" | "product" | null;
const navigation: { name: Section; icon: typeof LayoutDashboard }[] = [
  { name: "Visão geral", icon: LayoutDashboard }, { name: "Vendas", icon: ShoppingCart }, { name: "Clientes", icon: UsersRound }, { name: "Produtos", icon: Boxes }, { name: "Estoque", icon: ClipboardList }, { name: "Financeiro", icon: CircleDollarSign }, { name: "Configurações", icon: Settings },
];

export default function Home() {
  const [section, setSection] = useState<Section>("Visão geral");
  const [menuOpen, setMenuOpen] = useState(false);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [customers, setCustomers] = useState(initialCustomers);
  const [products, setProducts] = useState(initialProducts);
  const [query, setQuery] = useState("");
  const lowStock = products.filter((p) => p.quantity <= p.minimumStock);
  const inventoryValue = useMemo(() => products.reduce((total, p) => total + p.quantity * p.price, 0), [products]);
  const visibleCustomers = customers.filter((c) => c.name.toLowerCase().includes(query.toLowerCase()));
  const visibleProducts = products.filter((p) => p.name.toLowerCase().includes(query.toLowerCase()));
  const action = section === "Clientes" ? <Action label="Novo cliente" icon={<Plus className="size-4" />} onClick={() => setDialog("customer")} /> : section === "Produtos" ? <Action label="Novo produto" icon={<PackagePlus className="size-4" />} onClick={() => setDialog("product")} /> : null;

  function createCustomer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setCustomers((items) => [{ id: crypto.randomUUID(), name: String(data.get("name")), phone: String(data.get("phone")), email: String(data.get("email")), lastPurchase: "Novo", totalSpent: 0 }, ...items]); setDialog(null); }
  function createProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setProducts((items) => [{ id: crypto.randomUUID(), name: String(data.get("name")), category: String(data.get("category")), sku: String(data.get("sku")), quantity: Number(data.get("quantity")), minimumStock: Number(data.get("minimumStock")), price: Number(data.get("price")) }, ...items]); setDialog(null); }

  return <div className="min-h-svh bg-stone-100 text-stone-800">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col bg-stone-950 px-4 py-5 text-stone-200 transition-transform lg:translate-x-0 ${menuOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center gap-3 px-3"><Image src="/logo-uai.jpg" alt="Uai Tabacaria e Adega" width={48} height={48} className="rounded-lg bg-white object-contain p-1" priority /><div><p className="font-bold text-white">UAI ERP</p><p className="text-xs text-stone-400">Tabacaria e Adega</p></div><button className="ml-auto lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X className="size-5" /></button></div>
      <nav className="mt-9 space-y-1" aria-label="Navegação principal">{navigation.map(({ name, icon: Icon }) => <button key={name} onClick={() => { setSection(name); setMenuOpen(false); setQuery(""); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${section === name ? "bg-amber-500 text-stone-950" : "text-stone-300 hover:bg-stone-800 hover:text-white"}`} aria-current={section === name ? "page" : undefined}><Icon className="size-[18px]" />{name}</button>)}</nav>
      <div className="mt-auto rounded-xl border border-stone-800 bg-stone-900 p-4"><p className="text-xs font-bold tracking-widest text-amber-400">AMBIENTE DE DEMONSTRAÇÃO</p><p className="mt-2 text-xs leading-5 text-stone-400">Dados de exemplo. Banco, login e permissões entram antes do uso operacional.</p></div>
    </aside>
    {menuOpen && <button aria-label="Fechar navegação" className="fixed inset-0 z-30 bg-black/45 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <main className="min-h-svh lg:ml-72"><header className="flex h-16 items-center gap-4 border-b border-stone-200 bg-white px-5 sm:px-8"><button className="lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Abrir menu"><Menu className="size-5" /></button><div className="relative ml-auto w-full max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-stone-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={section === "Clientes" ? "Buscar cliente" : section === "Produtos" || section === "Estoque" ? "Buscar produto" : "Buscar no ERP"} className="w-full rounded-lg border border-stone-200 bg-stone-50 py-2 pl-9 pr-3 text-sm outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100" /></div><div className="hidden border-l border-stone-200 pl-4 text-right sm:block"><p className="text-sm font-semibold">Administrador</p><p className="text-xs text-stone-500">Operação Uai</p></div></header>
      <div className="mx-auto max-w-7xl p-5 sm:p-8">{section === "Visão geral" && <Dashboard customers={customers} lowStock={lowStock} inventoryValue={inventoryValue} onStock={() => setSection("Estoque")} />}{section === "Clientes" && <Customers items={visibleCustomers} action={action} />}{section === "Produtos" && <Products items={visibleProducts} action={action} />}{section === "Estoque" && <Stock items={visibleProducts} lowStock={lowStock} />}{["Vendas", "Financeiro", "Configurações"].includes(section) && <Planned section={section} />}</div>
    </main>
    {dialog === "customer" && <Modal title="Novo cliente" onClose={() => setDialog(null)}><form onSubmit={createCustomer} className="space-y-4"><Field label="Nome completo" name="name" required /><Field label="Telefone" name="phone" required /><Field label="E-mail" name="email" type="email" /><FormActions onCancel={() => setDialog(null)} /></form></Modal>}
    {dialog === "product" && <Modal title="Novo produto" onClose={() => setDialog(null)}><form onSubmit={createProduct} className="grid gap-4 sm:grid-cols-2"><Field label="Nome" name="name" required extraClass="sm:col-span-2" /><Field label="Categoria" name="category" required /><Field label="SKU" name="sku" required /><Field label="Estoque inicial" name="quantity" type="number" min="0" defaultValue="0" required /><Field label="Estoque mínimo" name="minimumStock" type="number" min="0" defaultValue="0" required /><Field label="Preço de venda" name="price" type="number" min="0" step="0.01" required /><div className="sm:col-span-2"><FormActions onCancel={() => setDialog(null)} /></div></form></Modal>}
  </div>;
}

function Title({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.18em] text-amber-700">UAI ERP</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-stone-950">{title}</h1><p className="mt-2 text-sm text-stone-500">{description}</p></div>{action}</div>; }
function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="font-bold text-stone-900">{title}</h2>{action}</div>{children}</section>; }
function Stat({ label, value, hint, warning }: { label: string; value: string; hint: string; warning?: boolean }) { return <article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-stone-500">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight text-stone-950">{value}</p><p className={`mt-2 text-xs font-semibold ${warning ? "text-amber-700" : "text-emerald-700"}`}>{hint}</p></article>; }
function Dashboard({ customers, lowStock, inventoryValue, onStock }: { customers: Customer[]; lowStock: Product[]; inventoryValue: number; onStock: () => void }) { return <><Title title="Visão geral" description="Acompanhe o que precisa de atenção na operação hoje." /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Vendas do mês" value="R$ 18.460,00" hint="↑ 12,4% no período" /><Stat label="Pedidos em aberto" value="14" hint="3 novos hoje" /><Stat label="Clientes ativos" value={String(customers.length)} hint="Base em crescimento" /><Stat label="Estoque baixo" value={String(lowStock.length).padStart(2, "0")} hint="Requer reposição" warning /></section><section className="mt-7 grid gap-6 lg:grid-cols-2"><Panel title="Produtos que exigem atenção" action={<button onClick={onStock} className="text-sm font-semibold text-amber-700">Abrir estoque</button>}>{lowStock.map((p) => <div key={p.id} className="flex items-center justify-between border-t border-stone-100 py-4 first:border-0 first:pt-0"><div><p className="font-semibold">{p.name}</p><p className="mt-1 text-xs text-stone-500">{p.sku} · mínimo {p.minimumStock} un.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">{p.quantity} un.</span></div>)}</Panel><Panel title="Resumo de estoque"><div className="rounded-xl bg-stone-50 p-5"><p className="text-sm text-stone-500">Valor estimado em estoque</p><p className="mt-2 text-3xl font-bold text-stone-950">{money.format(inventoryValue)}</p><p className="mt-4 text-xs font-semibold text-emerald-700">Controle por SKU preparado</p></div></Panel></section></>; }
function Customers({ items, action }: { items: Customer[]; action: ReactNode }) { return <><Title title="Clientes" description="Cadastre e acompanhe sua base de relacionamento." action={action} /><Panel title={`${items.length} cliente(s) encontrado(s)`}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-stone-400"><tr><th className="pb-3">Cliente</th><th className="pb-3">Contato</th><th className="pb-3">Última compra</th><th className="pb-3 text-right">Total</th></tr></thead><tbody>{items.map((c) => <tr key={c.id} className="border-t border-stone-100"><td className="py-4"><p className="font-semibold">{c.name}</p><p className="text-xs text-stone-500">{c.email || "Sem e-mail"}</p></td><td className="py-4">{c.phone}</td><td className="py-4">{c.lastPurchase}</td><td className="py-4 text-right font-semibold">{money.format(c.totalSpent)}</td></tr>)}</tbody></table></div>{!items.length && <Empty label="Nenhum cliente encontrado." />}</Panel></>; }
function Products({ items, action }: { items: Product[]; action: ReactNode }) { return <><Title title="Produtos" description="Catálogo central para PDV, estoque e financeiro." action={action} /><ProductTable items={items} /></>; }
function Stock({ items, lowStock }: { items: Product[]; lowStock: Product[] }) { return <><Title title="Estoque" description={`${lowStock.length} item(ns) precisa(m) de reposição.`} /><ProductTable items={items} details /></>; }
function ProductTable({ items, details = false }: { items: Product[]; details?: boolean }) { return <Panel title={`${items.length} produto(s) listado(s)`}><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-stone-400"><tr><th className="pb-3">Produto</th><th className="pb-3">Categoria</th><th className="pb-3">SKU</th><th className="pb-3">Estoque</th><th className="pb-3 text-right">Preço</th></tr></thead><tbody>{items.map((p) => { const low = p.quantity <= p.minimumStock; return <tr key={p.id} className="border-t border-stone-100"><td className="py-4 font-semibold">{p.name}</td><td className="py-4">{p.category}</td><td className="py-4 font-mono text-xs text-stone-500">{p.sku}</td><td className="py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${low ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{p.quantity} un. {details && `· mín. ${p.minimumStock}`}</span></td><td className="py-4 text-right font-semibold">{money.format(p.price)}</td></tr>; })}</tbody></table></div>{!items.length && <Empty label="Nenhum produto encontrado." />}</Panel>; }
function Planned({ section }: { section: Section }) { const descriptions: Partial<Record<Section, string>> = { Vendas: "O PDV será conectado ao catálogo, clientes e movimento de estoque.", Financeiro: "Contas a pagar, receber e conciliação entrarão após as regras fiscais.", Configurações: "Usuários, perfis de acesso e parâmetros da empresa serão centralizados aqui." }; return <section className="mx-auto max-w-2xl py-16 text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-amber-100 text-amber-800"><BarChart3 className="size-7" /></div><h1 className="mt-6 text-3xl font-bold text-stone-950">{section}</h1><p className="mx-auto mt-3 max-w-lg leading-7 text-stone-600">{descriptions[section]} Este módulo seguirá a mesma base de dados e permissões.</p></section>; }
function Action({ label, icon, onClick }: { label: string; icon: ReactNode; onClick: () => void }) { return <button onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-lg bg-stone-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-stone-800">{icon}{label}</button>; }
function Empty({ label }: { label: string }) { return <div className="py-10 text-center text-sm text-stone-500">{label}</div>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/50 p-4" role="dialog" aria-modal="true" aria-label={title}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-lg font-bold text-stone-950">{title}</h2><button onClick={onClose} className="rounded-lg p-1 text-stone-500 hover:bg-stone-100" aria-label="Fechar"><X className="size-5" /></button></div>{children}</div></div>; }
function Field({ label, name, type = "text", extraClass = "", ...props }: { label: string; name: string; type?: string; extraClass?: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className={`block text-sm font-semibold text-stone-700 ${extraClass}`}>{label}<input name={name} type={type} className="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2.5 font-normal outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100" {...props} /></label>; }
function FormActions({ onCancel }: { onCancel: () => void }) { return <div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-stone-600 hover:bg-stone-100">Cancelar</button><button type="submit" className="rounded-lg bg-stone-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-stone-800">Salvar</button></div>; }
